name: CI - Build and Test Keyshift

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build_and_test:
    # Replace with ubuntu-latest after
    # https://github.com/actions/runner-images/issues/10636
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Pull digestpp

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Build succeeds (without Catch2)
        run: ./build_minimal.sh

      - name: Install Catch2
        run: sudo apt-get install -y catch2

      - name: Run full build and test script
        run: ./build_all_and_test.sh
